#!/bin/sh

distros=(
    "AlmaLinux"
    "AlpineLinux"
    "AltLinux"
    "AnarchyLinux"
    "antergos"
    "antiXLinux"
    "archbang"
    "archlinux"
    "ArcoLinux"
    "AsahiLinux"
    "BackBox"
    "bedrocklinux"
    "BlackArchOfficial"
    "bodhilinux"
    "cachyos"
    "CentOS"
    "chromeos"
    "ClearLinux"
    "CrunchBang"
    "crunchbangplusplus"
    "cruxlinux"
    "debian"
    "deepin"
    "elementaryos"
    "EndeavourOS"
    "exherbo"
    "Fedora"
    "FerenOS"
    "GarudaLinux"
    "geckolinux"
    "Gentoo"
    "GUIX"
    "holoiso"
    "kaos"
    "Kalilinux"
    "kdeneon"
    "kinoite"
    "kisslinux"
    "Kubuntu"
    "Lubuntu"
    "linuxfromscratch"
    "LinuxLite"
    "linuxmint"
    "Mageia"
    "ManjaroLinux"
    "MXLinux"
    "NixOS"
    "NobaraProject"
    "OfficialArchLabsLinux"
    "OpenMandriva"
    "openSUSE"
    "OracleLinux"
    "Parabola"
    "ParrotOS"
    "PeppermintOS"
    "pop_os"
    "puppylinux"
    "Q4OS"
    "Qubes"
    "raspbian"
    "RedStarOS"
    "redhat"
    "rhinolinux"
    "rlxos_dev"
    "RockyLinux"
    "sabayon"
    "scientificlinux"
    "slackware"
    "SolusProject"
    "SteamOS"
    "tails"
    "tinycorelinux"
    "Ubuntu"
    "vanillaos"
    "venomlinux"
    "voidlinux"
    "Whonix"
    "xubuntu"
    "zorinos"
)

printf "\n"
printf "Fetched "

for distro in "${distros[@]}"; do
    curl -s -o "$distro.html" "https://www.reddit.com/r/$distro/?rdt=11111"
    printf "%s, " "$distro"
done

printf "\n\nPopularity is as Follows:\n\n"

for distro in "${distros[@]}"; do
    number=$(grep -m 1 '<faceplate-number number' "$distro.html" | awk -F'"' '{print $2}')
    echo "$distro: $number"
done | sort -t ':' -k2nr

rm -rf *.html
